config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'pages/forbidden'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get  '/events',     to: 'events#index', as: :events
  post '/events',     to: 'events#create'
  get  '/events/new', to: 'events#new',   as: :new_event
  get  '/events/:id', to: 'events#show',  as: :event
  get  '/events/:id/edit', to: 'events#edit', as: :edit_event 
  patch '/events/:id/', to: 'events#update', as: :update_event
  delete '/events/:id', to: 'events#destroy', as: :destroy_event

  get '/login', to: 'users#login', as: :login

  post '/sign_in', to: 'users#sign_in', as: :sign_in

  delete '/sign_out', to: 'users#sign_out', as: :sign_out
  # localhost:3000/events
  # events_path
  # localhost:3000/events/10
  # event_path(10)
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login, only: [:new, :create, :destroy, :edit, :update]
  helper_method :current_user
  private

  def require_login
    if !session.has_key? :user_id
      redirect_to login_path
    end
  end

  def current_user
    if session.has_key? :user_id
      @user = User.find(session[:user_id])
      return @user
    else
      return nil
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :destroy, :update]

  def index
    @events = Event.all
  end

  def edit
    
  end

  def show
    
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end
  def update
    
    @event.name = params[:event][:name]
    @event.description = params[:event][:description]
    @event.save
    redirect_to event_path
  end
  def new
    @event = Event.new
  end

  def create
    Event.create(name: params[:event][:name], description: params[:event][:description])

    redirect_to root_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def forbidden
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def sign_out
    session.delete(:user_id)
    redirect_to root_path, notice: 'User successfully signed out'
  end

  def sign_in
    user_name = user_params[:name]
    @user = User.find_by_name(user_name)

    if @user.nil?
      redirect_to pages_forbidden_path, notice: 'User doesnt exist'
    elsif @user.password == user_params[:password]
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'User successfully sign in'
    else
      redirect_to pages_forbidden_path, notice: 'Incorrect password'
    end
  end

  def login
    @user = User.new
  end
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h3>Editar evento <%= @event.name %></h3>
<%= form_for(@event) do |form| %>
<p>
  <%= form.label :name, 'Nombre' %>
  <%= form.text_field :name %>
</p>
<p>
  <%= form.label :description, 'Descripción' %>
  <%= form.text_field :description %>
</p>
  <%= form.submit 'Crear Evento'%>
<% end %>

app/views/events/index.html.erb
<h1>Voletia</h1>
<h3>El sitio más cool para registrar eventos. (Made by Guirri)</h3>

<%= link_to 'Sign Out', sign_out_path, method: :delete%>
<ul>
  <% @events.each do |event| %>
    <li><%= link_to event.name, event_path(event.id) %></li>
  <% end %>
</ul>

<%= link_to 'Crear Evento', new_event_path %>

app/views/events/new.html.erb
<h3>Crea un evento</h3>
<%= form_for(@event) do |form| %>
<p>
  <%= form.label :name, 'Nombre' %>
  <%= form.text_field :name %>
</p>
<p>
  <%= form.label :description, 'Descripción' %>
  <%= form.text_field :description %>
</p>
  <%= form.submit 'Crear Evento'%>
<% end %>

app/views/events/show.html.erb
<h3><%= @event.name %></h3>
<p><%= @event.description %></p>
<%= link_to 'Regresar', root_path %>
<%= link_to 'Destruyete', @event, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voletia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_user.nil? %>
      Welcome <%= current_user.name %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/forbidden.html.erb
<h1>FORBIDDEN</h1>
<p id="notice"><%= notice %></p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h1>Login Here</h1>

<%= form_for(@user, url: sign_in_path(@user)) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>